### PR TITLE
Update version to 2.0.0 and README.md with breaking changes 

### PR DESCRIPTION
**Pull request by cpaleop**
This PR includes a section in the `README.md` which clarifies the breaking changes version `2.0.0` introduces.

It also updates version to `2.0.0` to prepare for next major release.

Let me know if the updated documentation is clear enough and if you have any suggestions!

### CODE REVIEW

**Review by cmargonis — COMMENTED** [review]
The usage instructions of the `README.md` should be updated too, right?

**Comment by cpaleop** [comment]
> The usage instructions of the `README.md` should be updated too, right?

Which part exactly? :thinking:

**Review by ChryssaAliferi — APPROVED** [review]
For some reason 😞 (probably my fault) the part about `EmojiCompatUtils` `EmojInitListener` was already missing from the README.md file. If @cmargonis does not mean something else and as far as I can see, this looks correct to me.
PS: Let's no forget to add the breaking changes the tag log when version gets released as well. 💪

**Comment by cmargonis** [comment]
Yes you are right @ChryssaAliferi 🤣

**Pull request merged**
