### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by ChryssaAliferi**
This PR:

- Applies gradle version catalogue
- Updates all dependencies to the latest versions
- Updates JAVA to 19.

### CODE REVIEW

**Comment by cmargonis** [comment]
Closing this as it got superseded by #22 😊 Thank you!

**Comment by ChryssaAliferi** [comment]
> Closing this as it got superseded by #22 😊 Thank you!

Not exactly but ok! 😊

**Comment by cmargonis** [comment]
> > Closing this as it got superseded by #22 😊 Thank you!
> 
> Not exactly but ok! 😊

Apologies if the intention was different 😇 Feel free to reopen it if that's the case! 😁

**Comment by ChryssaAliferi** [comment]
> > > Closing this as it got superseded by #22 😊 Thank you!
> > 
> > 
> > Not exactly but ok! 😊
> 
> Apologies if the intention was different 😇 Feel free to reopen it if that's the case! 😁

Just for reference, there were changes regarding migration to version catalogues that are not "superseded".

**Comment by cmargonis** [comment]
> > > > Closing this as it got superseded by #22 😊 Thank you!
> > > 
> > > 
> > > Not exactly but ok! 😊
> > 
> > 
> > Apologies if the intention was different 😇 Feel free to reopen it if that's the case! 😁
> 
> Just for reference, there were changes regarding migration to version catalogues that are not "superseded".

Yes! Maybe we should have asked first, again apologies!

**Pull request closed without merging**
